/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
    ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine']
    ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const ALayout: typeof import('@arco-design/web-vue')['Layout']
  const ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
  const ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
  const ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
  const ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine']
  const ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
  const ASpace: typeof import('@arco-design/web-vue')['Space']
  const ASwitch: typeof import('@arco-design/web-vue')['Switch']
  const ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}