/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AEmpty: typeof import('@arco-design/web-vue')['Empty']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AMenuItemGroup: typeof import('@arco-design/web-vue')['MenuItemGroup']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
    ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine']
    ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASpin: typeof import('@arco-design/web-vue')['Spin']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph']
    Chat: typeof import('./components/Chat.vue')['default']
    Contenteditable: typeof import('./components/contenteditable/Contenteditable.vue')['default']
    ContenteditableNode: typeof import('./components/contenteditable/ContenteditableNode.vue')['default']
    IconFont: typeof import('./components/icons/IconFont.vue')['default']
    MentionList: typeof import('./components/contenteditable/mention/MentionList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tiptap: typeof import('./components/contenteditable/Tiptap.vue')['default']
  }
}

// For TSX support
declare global {
  const AAvatar: typeof import('@arco-design/web-vue')['Avatar']
  const ADoption: typeof import('@arco-design/web-vue')['Doption']
  const ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
  const AEmpty: typeof import('@arco-design/web-vue')['Empty']
  const AInput: typeof import('@arco-design/web-vue')['Input']
  const ALayout: typeof import('@arco-design/web-vue')['Layout']
  const ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
  const ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
  const AList: typeof import('@arco-design/web-vue')['List']
  const AListItem: typeof import('@arco-design/web-vue')['ListItem']
  const AMenu: typeof import('@arco-design/web-vue')['Menu']
  const AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
  const AMenuItemGroup: typeof import('@arco-design/web-vue')['MenuItemGroup']
  const APopover: typeof import('@arco-design/web-vue')['Popover']
  const AScrollbar: typeof import('@arco-design/web-vue')['Scrollbar']
  const ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
  const ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine']
  const ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
  const ASpace: typeof import('@arco-design/web-vue')['Space']
  const ASpin: typeof import('@arco-design/web-vue')['Spin']
  const ASwitch: typeof import('@arco-design/web-vue')['Switch']
  const ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
  const ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph']
  const Chat: typeof import('./components/Chat.vue')['default']
  const Contenteditable: typeof import('./components/contenteditable/Contenteditable.vue')['default']
  const ContenteditableNode: typeof import('./components/contenteditable/ContenteditableNode.vue')['default']
  const IconFont: typeof import('./components/icons/IconFont.vue')['default']
  const MentionList: typeof import('./components/contenteditable/mention/MentionList.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Tiptap: typeof import('./components/contenteditable/Tiptap.vue')['default']
}